name: nextcloudnotes
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  injectable: ^2.1.1
  get_it: ^7.6.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  auto_route: ^7.1.0
  dio: ^5.1.2
  flutter_secure_storage: ^8.0.0
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  webview_flutter: ^4.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  eva_icons_flutter: ^3.1.0
  intl: ^0.18.1
  nixi_markdown: ^0.1.0
  flutter_markdown: ^0.6.10+6
  flutter_inappwebview: ^6.0.0-beta.23
  logger: ^1.3.0
  flutter_platform_widgets: ^3.3.4
  pull_down_button: ^0.9.1
  keyboard_actions: ^4.2.0
  connectivity_plus: ^4.0.1
  settings_ui: ^2.0.2
  flash: ^3.0.5+1
  cached_network_image: ^3.2.3

dev_dependencies:
  auto_route_generator: ^7.0.0
  injectable_generator: ^2.1.5
  mobx_codegen: ^2.3.0
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
